### ISSUE TITLE
reader_basemap_landmask fails if there is only one particle 

### ISSUE THREAD

**Issue by simonweppe** [OpenDrift/opendrift#71] opened 2018-04-12 23:27 UTC
Hi there,

The polygon checking appears to fail if there is only one particle in the model. This seems to be because of the way numpy handles this :
        # np.int32(np.array([1])) = 1 , but
        # np.int32(np.array([1,1]) = array([1,1]) - an array is expected for np.clip to work
See a workaround below which seems to work (in reader_basemap_landmask.py):

    def on_land(self, x, y):
        #return [self.map.is_land(x0, y0) for x0,y0 in zip(x,y)]  # uncomment for simulation in lakes
        x0 = (x - self.bmap_raster.xmin)/self.bmap_raster.resolution
        y0 = (y - self.bmap_raster.ymin)/self.bmap_raster.resolution
        x0 = np.int32(x0)
        y0 = self.bmap_raster.data.shape[0] - np.int32(y0) - 1

        # if only there is only one particle, 
        # np.int32(x0) will make x0 an int32, and not an array.  This will make np.clip to fail
        # This is because 
        # np.int32(np.array([1])) = 1 , while
        # np.int32(np.array([1,1]) = array([1,1])
        # 
        # convert to array if needed
        if type(x0) == np.int32: 
            x0 = np.array([x0])
            y0 = np.array([y0])
        
        #Clip out of bounds
        np.clip(x0, 0, self.bmap_raster.data.shape[1]-1, out=x0)
        np.clip(y0, 0, self.bmap_raster.data.shape[0]-1, out=y0)
        
        land = (self.bmap_raster.data[y0, x0] == 0)
        coords = np.flatnonzero(land)
        logging.debug('Checking ' + str(len(coords)) + ' of ' + str(len(x)) + ' coordinates to polygons')
        
        if (len(coords) > 0):
            land[coords] = self.on_land_polycheck(x[coords], y[coords])
        
        return land

**Comment by knutfrode** [comment] 2018-04-13 10:39
Thank you Simon, this seems useful.
However, I have never encountered any problem with single elements and polygon/land checking.
Do you have a small example which reproduces the error you get?

**Comment by simon-msl** [comment] 2018-04-16 00:25
Hi Knut,

For example, I'd get the error if I modify the example in */examples/example.py* to release a single particle at the first time step : 
e.g. 
`Seed oil elements at defined position and time`
`o.seed_elements(lon, lat, radius=50, number=1, time=time[], wind_drift_factor=.02)`

Can you reproduce ? might be related to numpy version ? (I have numpy 1.13.3)

**Comment by knutfrode** [comment] 2018-04-16 07:55
Hi,

This seems to work fine for me, also with a single particle. In time step 65, land_binary_mask is 1 (land is encountered), and the simulation stops. 
Numpy 1.13.3 is also among the versions which is [automatically tested](https://travis-ci.org/OpenDrift/opendrift/builds/355398709?utm_source=github_status&utm_medium=notification
) with unit-tests.

What might perhaps be confusing, is that a ValueError is raised when there is no more particles left. Howver, this is intended behaviour, just to tell the user that the simulation stopped before the scheduled end (because there are no more elements).

**Comment by simon-msl** [comment] 2018-04-16 09:04
Thanks Knut ...interesting..and surprising !
For me it didnt even run the first time step, it crashed before on the very first 'on_land' check.

I actually just tried this on a linux machine :
np.int32(np.array([1])) and got [1] as a result (while my windows box would yield  1 i.e. not an array). 

So indeed, there would be no need for my additional code there. Thanks for having a look !

**Comment by knutfrode** [comment] 2018-04-18 09:15
Yes, this is surprising.
I now committed an [update](https://github.com/OpenDrift/opendrift/commit/c18edcd225c42bd178c6c6e5f9315667a398d87a) which should hopefully work for both Linux and Windows.
Could you please test this on Windows? I do not have any Windows machines myself, and [Travis](https://travis-ci.org/OpenDrift/opendrift/builds/368047402?utm_source=github_status&utm_medium=notification) only checks various Linux systems.

**Comment by simon-msl** [comment] 2018-04-18 20:55
Yes it works ! Thanks for the edit.

**Closed** 2019-08-08 12:46 UTC
